# Lychee link checker configuration
timeout = 20
max_retries = 3
retry_wait_time = 2
user_agent = "lychee-ci (+https://github.com/lycheeverse/lychee)"

# Accept common success/redirect/rate-limit statuses
accept = [200, 204, 206, 301, 302, 429]

# Ignore flaky or rate-limited domains and non-http schemes
exclude = [
  "mailto:*",
  "nostr:*",
  "https://x.com/.*",
  "https://twitter.com/.*",
  "https://snort.social/.*",
  "https://medium.com/.*",
  "https://www.youtube.com/.*",
]
