name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Prettier check
        run: npm run format:check

      - name: Lint (all)
        run: npm run lint:all

      - name: Type check (astro)
        run: npm run typecheck

      - name: Workers type check
        run: npm run typecheck:workers

      - name: Markdown links (remark)
        run: npm run lint:links

      - name: Dead code (ts-prune)
        run: npx ts-prune -p tsconfig.json | tee ts-prune.out || true
        continue-on-error: true

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-dist-${{ matrix.node }}
          path: dist
          retention-days: 7
