name: Link Check

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1" # Weekly, Mondays at 06:00 UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check links in built site and content
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --no-progress --max-concurrency 4
            --config lychee.toml
            "dist/**/*.html" "README.md" "src/content/**/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
